# Send anonymous data statistics
# e.g. player count, minecraft version
metrics-enabled: true

# Chart settings
chart:
  # Chart width in characters
  width: 40
  # Chart height in characters
  height: 12
  # Chart date format
  date-format: "dd MMM yyyy"